### ISSUE TITLE
Laravel 5.6 - Call to a member function make() on null

### ISSUE THREAD

**Issue by stojan014** [zofe/rapyd-laravel#437]
Hi,
I installed version 2.2 to Laravel 5.6. After first start I got  error message " Call to a member function make() on null " on path vendor\zofe\rapyd\src\Rapyd.php. 

`$grid = DataGrid::source( Reminder::with('name'))->getSet();  //same source types of DataSet
        
        $grid->add('name','Name', true); //field name, label, sortable
        $grid->add('email','email'); //relation.fieldname
        $grid->add('{{ substr($body,0,20) }}...','Body'); //blade syntax with main field
        $grid->add('{{ $author->firstname }}','Author'); //blade syntax with related field
        $grid->add('body|strip_tags|substr[0,20]','Body'); //filter (similar to twig syntax)
        $grid->add('custom_message','Body')->filter('strip_tags|substr[0,20]'); //another way to filter
        $grid->edit('/articles/edit', 'Edit','modify|delete'); //shortcut to link DataEdit actions
        
        //cell closure
        $grid->add('revision','Revision')->cell( function( $value, $row) {
            return ($value != '') ? "rev.{$value}" : "no revisions for art. {$row->id}";
        });
            
            //row closure
            $grid->row(function ($row) {
                if ($row->cell('public')->value < 1) {
                    $row->cell('title')->style("color:Gray");
                    $row->style("background-color:#CCFF66");
                }
            });
                
                $grid->link('/articles/edit',"Add New", "TR");  //add button
                $grid->orderBy('article_id','desc'); //default orderby
                $grid->paginate(10); //pagination
                echo 'Broj'.$grid->data->toBase()->count();
        return        view('home', compact('grid'));`

 Could you help me?

**Comment by zofe** [comment]
I'll try to support the 5.6 in next days

**Comment by abmcr** [comment]
I have try to install but i get an error when i launch composer 
`$ composer require zofe/rapyd
Using version ^2.6 for zofe/rapyd
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 6 installs, 0 updates, 0 removals
  - Installing zofe/burp (2.0.3): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing guzzlehttp/psr7 (1.4.2): Loading from cache
  - Installing intervention/image (2.4.2): Loading from cache
  - Installing laravelcollective/html (v5.6.10): Loading from cache
  - Installing zofe/rapyd (2.6.2): Loading from cache
intervention/image suggests installing ext-imagick (to use Imagick based image processing.)
intervention/image suggests installing intervention/imagecache (Caching extension for the Intervention Image library)
zofe/rapyd suggests installing baum/baum (Allows to use the DataTree widget)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
PHP Warning:  Uncaught ErrorException: require(/Users/abmcr/projects/builder//routes/rapyd.php): failed to open stream: No such file or directory in/Users/abmcr/projects/builder/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php:71
Stack trace:
#0 /Users/abmcr/projects/builder/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php(71): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'require(/Users/...', '/Users/abmcr/pr...', 71, Array)
#1 /Users/abmcr/projects/builder/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php(71): require()
#2 /Users/abmcr/projects/builder/vendor/zofe/rapyd/src/RapydServiceProvider.php(32): Illuminate\Support\ServiceProvider->loadRoutesFrom('/Users/abmcr/pr...')
#3 [internal function]: Zofe\Rapyd\RapydServiceProvider->boot()
#4 /Users/abmcr/projects/builder/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#5 /Users/abmcr/projects/builder/vendor/laravel/framework/src/Illuminate in /Users/abmcr/projects/builder/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php on line 71
PHP Fatal error:  Illuminate\Support\ServiceProvider::loadRoutesFrom(): Failed opening required '/Users/abmcr/projects/builder//routes/rapyd.php' (include_path='.:/usr/local/Cellar/php/7.2.4_1/share/php/pear') in /Users/abmcr/projects/builder/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php on line 71

In ServiceProvider.php line 71:

  Illuminate\Support\ServiceProvider::loadRoutesFrom(): Failed opening requir
  ed '/Users/abmcr/projects/builder//routes/rapyd.php' (include_path='.:/usr/
  local/Cellar/php/7.2.4_1/share/php/pear')


Script @php artisan package:discover handling the post-autoload-dump event returned with error code 255`

I have created manualy an empty rapyd.php into the routes folder

**Comment by anthonymanzo** [comment]
I'm getting the same error, it looks like there's an extra / on the end of the path to the published route (your error l#5).

**Comment by anthonymanzo** [comment]
More specifically, it's part of the artisan package:discover script

**Comment by abmcr** [comment]
For me Laravel 5.6 and last rapyd

**Comment by anthonymanzo** [comment]
I'm laravel 5.6 php 7.1

**Comment by zofe** [comment]
roger, write permissions problem, I'll check L5.6  documentation to write a fix in next hours

**Comment by zofe** [comment]
I think it's ok now with 2.6.6

basically installation is now:

    $ composer require zofe/rapyd
    $ php artisan vendor:publish  

(at the publish command question you should check: rapyd provider, and "routes")
Note, your db connection should e valid to run rapyd demos

thanks to all.

**Comment by abmcr** [comment]
Ok thank you
Now i get an error when i use rapy-demo route : in rapyd-demo/filter but also in rapyd-demo/edit...



ErrorException 
…/vendor/zofe/rapyd/src/DataForm/Field/Tags.php58

"count(): Parameter must be an array or an object that implements Countable"

line 58: if (count($this->local_options)) {

PHP 7.2

Ciao!

**Comment by zofe** [comment]
@abmcr  https://github.com/zofe/rapyd-laravel/blob/master/src/DataForm/Field/Tags.php#L19
change to: `public $local_options = []; `  in your vendor, then  tell me if it works so I can apply the fix.

**Comment by abmcr** [comment]
This work fine!
Thank you

**Comment by stojan014** [comment]
Everything works . Thanks for help!

**Comment by zofe** [comment]
you're welcome
